import ExpertStrip from './ExpertStrip';
import ContactForm from './ContactForm';
import CTA from './CTA';
import ReactMarkdown from 'react-markdown';

export default function ServiceLayout({page,type='service'}){
  const isInsight = type === 'insight';
  const faqs = (page.faqs || []).map((faq) => Array.isArray(faq) ? {question: faq[0], answer: faq[1]} : faq);
  const formattedDate = page.date ? new Intl.DateTimeFormat('en-AE', {dateStyle: 'long'}).format(new Date(page.date)) : null;

  return <><section className="contentGrid"><aside className="toc"><p className="eyebrow">On this page</p><a href="#overview">Overview</a>{!isInsight&&<><a href="#who">Who it helps</a><a href="#process">Process</a></>}<a href="#faq">FAQ</a><a href="#contact">Contact</a></aside><article className="longContent" id="overview"><p className="badge">{page.category||'Insight'}</p>{(formattedDate||page.author)&&<p className="articleMeta">{formattedDate}{formattedDate&&page.author?' · ':''}{page.author&&`By ${page.author}`}</p>}{page.image&&<img className="articleImage" src={page.image} alt={page.imageAlt||page.title}/>} {isInsight&&page.body?<ReactMarkdown>{page.body}</ReactMarkdown>:page.sections.map((p,i)=><p key={i}>{p}</p>)}{page.keywords?.length>0&&<div className="keywordList">{page.keywords.map(k=><span key={k}>{k}</span>)}</div>}{!isInsight&&<><h2 id="who">Who this is for</h2><ul>{(page.forWho||['Clients who need structured legal orientation before taking action','Visitors who want practical next steps instead of generic information']).map(x=><li key={x}>{x}</li>)}</ul><h2 id="process">Recommended process</h2><ol>{(page.process||['Clarify the facts','Collect documents','Review options','Decide the next step']).map(x=><li key={x}>{x}</li>)}</ol></>} {faqs.length>0&&<><h2 id="faq">Frequently asked questions</h2>{faqs.map(({question,answer})=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</>}</article></section><ExpertStrip compact/><CTA title={`Discuss ${page.title}`} text="Use the form below or send an e-mail directly. The site is built to convert legal questions into structured intake."/><section className="contactBlock" id="contact"><div><p className="eyebrow">Contact form</p><h2>Start with a clear message</h2><p>Share the matter, relevant country, document status and any urgent deadlines.</p></div><ContactForm defaultService={page.title}/></section></>}
